### ISSUE TITLE
With VPN and chinese user still can't bypass region lock

### ISSUE THREAD

**Issue by zeemyself** [lunDreame/BambuProject#1]
<img width="926" alt="Screenshot 2024-04-21 at 4 03 27 AM" src="https://github.com/lunDreame/BambuProject/assets/5433120/68d7d667-1368-4481-aba6-c2821221cb10">

Have both chinese account and activate VPN still no luck

**Comment by lunDreame** [comment]
At first, it started for domestic use, but now we are only using the global version. The actual test was conducted in the global version. Therefore, it is difficult to give you information because there is no test for domestic use. If possible, would you like to port forward the printer address? 3000 ports

**Comment by zeemyself** [comment]
Why forward port anyway? even though I can forward port but my ISP doesn't give out public ip anymore so can't access it.

Also I just dig deep into your kr community with this post and get VPN set up and running
https://cafe.naver.com/bambulab/2821

Now I can bind it!
